apiVersion: v1
kind: Template
metadata:
  name: telemeter-metering
parameters:
- name: NAMESPACE
  value: telemeter-metering
- name: METERING_VERSION
  value: 0.11.0
objects:
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: meteringconfigs.metering.openshift.io
    annotations:
      catalog.app.coreos.com/description: An instance of Metering
      catalog.app.coreos.com/displayName: Metering
  spec:
    group: metering.openshift.io
    version: v1alpha1
    scope: Namespaced
    names:
      plural: meteringconfigs
      singular: meteringconfig
      kind: MeteringConfig
      listKind: MeteringConfigList

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: hivetables.metering.openshift.io
    annotations:
      catalog.app.coreos.com/displayName: "Metering Presto Table"
      catalog.app.coreos.com/description: "A table within PrestoDB"
  spec:
    group: metering.openshift.io
    version: v1alpha1
    scope: Namespaced
    names:
      plural: hivetables
      singular: hivetable
      kind: HiveTable

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: prestotables.metering.openshift.io
    annotations:
      catalog.app.coreos.com/displayName: "Metering Presto Table"
      catalog.app.coreos.com/description: "A table within PrestoDB"
  spec:
    group: metering.openshift.io
    version: v1alpha1
    scope: Namespaced
    names:
      plural: prestotables
      singular: prestotable
      kind: PrestoTable

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: reports.metering.openshift.io
    annotations:
      catalog.app.coreos.com/displayName: "Metering Report"
      catalog.app.coreos.com/description: "A metering report for a specific time interval"
  spec:
    group: metering.openshift.io
    version: v1alpha1
    scope: Namespaced
    names:
      plural: reports
      kind: Report
    additionalPrinterColumns:
    - name: Query
      type: string
      JSONPath: .spec.query
    - name: Schedule
      type: string
      JSONPath: .status.schedule.period
    - name: Running
      type: string
      JSONPath: .status.conditions[?(@.type=="Running")].reason
    - name: Failed
      type: string
      JSONPath: .status.conditions[?(@.type=="Failure")].reason
    - name: Last Report Time
      type: string
      JSONPath: .status.lastReportTime
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: reportdatasources.metering.openshift.io
    annotations:
      catalog.app.coreos.com/displayName: "Metering data source"
      catalog.app.coreos.com/description: "A resource describing a source of data for usage by Report Generation Queries"
  spec:
    group: metering.openshift.io
    version: v1alpha1
    scope: Namespaced
    names:
      plural: reportdatasources
      singular: reportdatasource
      kind: ReportDataSource
      shortNames:
      - datasource
      - datasources
    additionalPrinterColumns:
    - name: Earliest Metric
      type: string
      JSONPath: .status.prometheusMetricImportStatus.earliestImportedMetricTime
    - name: Newest Metric
      type: string
      JSONPath: .status.prometheusMetricImportStatus.newestImportedMetricTime
    - name: Import Start
      type: string
      JSONPath: .status.prometheusMetricsImportStatus.importDataStartTime
    - name: Import End
      type: string
      JSONPath: .status.prometheusMetricsImportStatus.importDataEndTime
    - name: Last Import Time
      type: string
      JSONPath: .status.prometheusMetricsImportStatus.lastImportTime
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: reportqueries.metering.openshift.io
    annotations:
      catalog.app.coreos.com/displayName: "Metering generation query"
      catalog.app.coreos.com/description: "A SQL query used by Metering to generate reports"
  spec:
    group: metering.openshift.io
    version: v1alpha1
    scope: Namespaced
    names:
      plural: reportqueries
      singular: reportquery
      kind: ReportQuery
      shortNames:
      - rq
    additionalPrinterColumns:
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: storagelocations.metering.openshift.io
    annotations:
      catalog.app.coreos.com/displayName: "Metering storage location"
      catalog.app.coreos.com/description: "Represents a configurable storage location for Metering to store metering and report data"
  spec:
    group: metering.openshift.io
    version: v1alpha1
    scope: Namespaced
    names:
      plural: storagelocations
      kind: StorageLocation

- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: metering-operator
    namespace: ${NAMESPACE}
    labels:
      app: metering-operator
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: metering-operator
    template:
      metadata:
        labels:
          app: metering-operator
      spec:
        securityContext:
          runAsNonRoot: true
        containers:
        - name: metering-operator
          image: "quay.io/coreos/metering-helm-operator:${METERING_VERSION}"
          args: ["run-operator.sh"]
          imagePullPolicy: Always
          env:
          - name: HELM_RELEASE_CRD_NAME
            value: Metering
          - name: HELM_RELEASE_CRD_API_GROUP
            value: metering.openshift.io
          - name: HELM_CHART_PATH
            value: /openshift-metering-0.1.0.tgz
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HELM_HOST
            value: "127.0.0.1:44134"
          - name: HELM_WAIT
            value: "false"
          - name: HELM_RECONCILE_INTERVAL_SECONDS
            value: "30"
          - name: RELEASE_HISTORY_LIMIT
            value: "3"
          resources:
            requests:
              memory: "25Mi"
              cpu: "50m"
            limits:
              memory: "25Mi"
              cpu: "50m"
        - name: tiller
          image: "quay.io/coreos/metering-helm-operator:${METERING_VERSION}"
          args: ["tiller"]
          imagePullPolicy: Always
          env:
          - name: TILLER_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TILLER_HISTORY_MAX
            value: "3"
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "50m"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /liveness
              port: 44135
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readiness
              port: 44135
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        serviceAccount: metering-operator

- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: metering-operator
    namespace: ${NAMESPACE}
  rules:
    - apiGroups:
      - metering.openshift.io
      resources:
      - '*'
      verbs:
      - '*'
    - apiGroups:
      - ""
      resources:
      - pods
      - pods/attach
      - pods/exec
      - pods/portforward
      - pods/proxy
      verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - ""
      resources:
      - configmaps
      - endpoints
      - persistentvolumeclaims
      - replicationcontrollers
      - replicationcontrollers/scale
      - secrets
      - serviceaccounts
      - services
      - services/proxy
      verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - ""
      resources:
      - bindings
      - events
      - limitranges
      - namespaces/status
      - pods/log
      - pods/status
      - replicationcontrollers/status
      - resourcequotas
      - resourcequotas/status
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - events
      verbs:
      - create
      - update
      - patch
    - apiGroups:
      - ""
      resources:
      - namespaces
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - apps
      resources:
      - deployments
      - deployments/rollback
      - deployments/scale
      - statefulsets
      verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - batch
      resources:
      - cronjobs
      - jobs
      verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - extensions
      resources:
      - daemonsets
      - deployments
      - deployments/rollback
      - deployments/scale
      - replicasets
      - replicasets/scale
      - replicationcontrollers/scale
      verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - rbac.authorization.k8s.io
      resources:
      - rolebindings
      - roles
      verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - route.openshift.io
      resources:
      - routes
      verbs:
      - create
      - get
      - list
      - watch
      - update
      - delete
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: metering-operator
    namespace: ${NAMESPACE}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: metering-operator
  subjects:
  - kind: ServiceAccount
    name: metering-operator

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: metering-operator
    namespace: ${NAMESPACE}

- apiVersion: authorization.openshift.io/v1
  kind: ClusterRole
  metadata:
    name: openshift-reporting-operator-cluster-permissions
  rules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
  - apiGroups:
    - authorization.k8s.io
    resources:
    - subjectaccessreviews
    verbs:
    - create
  - apiGroups:
    - authentication.k8s.io
    resources:
    - tokenreviews
    verbs:
    - create

- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: reporting-operator-cluster-permissions
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: openshift-reporting-operator-cluster-permissions
  subjects:
  - kind: ServiceAccount
    name: reporting-operator
    namespace: ${NAMESPACE}

- apiVersion: metering.openshift.io/v1alpha1
  kind: Metering
  metadata:
    name: operator-metering
    namespace: ${NAMESPACE}
  spec:
    openshift-reporting:
      enabled: false
